### ISSUE TITLE
Implement graphicscomplex type

### ISSUE THREAD

**Issue by axkr** [jsxgraph/json2D_JSXGraph#2]
For this input:
```mma
data = Table[15 {Cos[t], Sin[t]}, {t, 0, 4*Pi, 4*Pi/5}];

Graphics[GraphicsComplex[data, {Line[{1, 2, 3, 4, 5, 6}], Point[{1, 2, 3, 4, 5}]}]]
```

the following JavaScript/JSON is created (see #1):
- https://jsfiddle.net/axelclk/yb6nLk23/

Another variant with different colors set:
- https://jsfiddle.net/axelclk/rfb25a3c/

`GraphicsComplex` should be implemented as "type", "coords", "data" JSON array, similar to the existing types.

**Comment by Haspeldor** [comment]
Thanks for the suggestion, it should be implemented now!
