### ISSUE TITLE
Create logarithmic scale on x/y axis if attributes are set in the json format

### ISSUE THREAD

**Issue by axkr** [jsxgraph/json2D_JSXGraph#5]
If Scaling is set to `"log"` create a logarithmic scaling on `x`or `y `axis.
If Scaling is set to `"none"` create a linear scaling on `x`or `y `axis.

```json
  "axes": {
    "hasaxes": true,
    "scaling": ["log", "log"]
  }
```

See example:
- https://jsfiddle.net/axelclk/3oke4a1n/2/

**Comment by Haspeldor** [comment]
Thank you for bringing this up, this feature was supposed to be implemented a while ago.
However setting "hasaxes": true instead of [true,true] lead to the scaling being skipped.
This has now been fixed and the example should work as expected!
